#!/bin/bash
echo "ALIVE OR NOT" > output
if [ $# >= 1 ]
then
	for i in "$@"
	do
		ping -c 1 rpi$i
		if [ $? == 0 ]
		then
			echo rpi$i is alive >> output
		else
			echo rpi$i is dead >> output
		fi
else
	for i in {01..18}
	do
		ping -c 1 rpi$i
		if [ $? == 0 ]
		then
			echo rpi$i is alive >> output
		else
			echo rpi$i is dead >> output
		fi
	done
fi
