#!/bin/bash

if [ $# -ge 1 ]
then
	for i in "$@"
	do
		ping -c 1 -W 1 rpi$i >/dev/null
		if [ $? == 0 ]
		then
			echo rpi$i is alive
		else
			echo rpi$i is dead
		fi
	done
else
	for i in {01..18}
	do
		ping -c 1 -W 1 rpi$i >/dev/null
		if [ $? == 0 ]
		then
			echo rpi$i is alive
		else
			echo rpi$i is dead
		fi
	done
fi
